# Generated by Django 4.2.6 on 2024-05-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customer'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'order'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'order item'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'product'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'shipping address'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
